//require('./test/testContact.js')
//require('./test/testCompany.js')
require('./test/testDeal.js')
// require('./test/testOwner.js')
// require('./test/testEngagement.js')
// require('./test/testCRM.js')
//require('./test/testUtil.js')